apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
  namespace: nextcloud
type: Opaque
stringData:
  POSTGRES_DB: $DB
  POSTGRES_USER: $DB_USER
  POSTGRES_PASSWORD: $DB_NEXTCLOUD_PASSWORD
  NEXTCLOUD_ADMIN_USER: $NEXTCLOUD_ADMIN_USER
  NEXTCLOUD_ADMIN_PASSWORD: $NEXTCLOUD_ADMIN_PASSWORD

